### ISSUE TITLE
Snaptron down 

### ISSUE THREAD

**Issue by lonsbio** [langmead-lab/snapr#19]
Hi 

The backend seems to be down, tried on `exons` and `genes`, common error is missing package on server

```
/bin/sh: tabix: command not found
```

Full error for `http://snaptron.cs.jhu.edu/tcga/exons?regions=IKZF1`

```
DataSource:Type	
loaded 50100 samples metadata
running tabix ./data/exons.bgz chr7:50304083-50405100
/bin/sh: tabix: command not found
Traceback (most recent call last):
  File ".//snaptron.py", line 413, in <module>
    main()
  File ".//snaptron.py", line 409, in main
    run_toplevel_AND_query(intervalq,rangeq,sampleq,idq,sample_map=sample_map,ra=ra)
  File ".//snaptron.py", line 331, in run_toplevel_AND_query
    (found_snaptron_ids,found_sample_ids) = query_regions(intervalq,rangeq,snaptron_ids,filtering=ra.result_count,region_args=ra)
  File ".//snaptron.py", line 247, in query_regions
    (ids,sids) = search_by_gene_name(gc,interval,rangeq,rquery,intron_filters=snaptron_ids,save_introns=filtering,print_header=print_header,region_args=region_args)
  File ".//snaptron.py", line 134, in search_by_gene_name
    (iids_,sids_) = runner.run_query()
  File "/data/gigatron/srav2_ahoc_snaptron/snquery.py", line 184, in run_query
    raise RuntimeError("%s returned non-0 exit code\n" % (self.full_cmd))
RuntimeError: tabix ./data/exons.bgz chr7:50304083-50405100  returned non-0 exit code
```

**Comment by ChristopherWilks** [comment]
looks like the server was restarted recently and the services didn't come up properly, they should be good now
